### ISSUE TITLE
Inconsistent coloring

### ISSUE THREAD

**Issue by PierBover** [corneliusio/svelte-sublime#1]
Look:

![image](https://user-images.githubusercontent.com/226483/45400133-8ca29f80-b610-11e8-8077-6d8d27c95fce.png)

```
<g>
	<rect class="background" width={element.width} height={element.height} rx="5"/>
</g>
```

**Comment by PierBover** [comment]
Sorry my syntax was wrong...

**Comment by corneliusio** [comment]
Actually, I am seeing an issue with the unquoted interpolated attribute values not closing out properly. It is actually valid to have those values unquoted (I never do which is why I never noticed the first one would bugger up the following attributes).

Thanks for pointing this out! I'm gonna reopen and try to get this fixed asap.

**Comment by corneliusio** [comment]
To @PierBover and anyone else who comes across this, looks like the issue runs a little deeper into the way I'm pulling in HTML scopes and rules and the fix will require a different approach. I've been needing to switch this over to working using [YAML-Macros](https://github.com/Thom1729/YAML-Macros) for a while now to clean things up, but I'll need to go ahead and do that sooner rather than later to address this.

Unfortunately, having wedding festivities the next two weekends so this will prob be a few weeks before I get to it—just know I haven't forgotten about it.

**Comment by corneliusio** [comment]
So, I ended up having an unexpectedly slow day at the office and decided to jump in on this—went about as smoothly as could have been hoped and I was able to basically rewrite the whole thing in just a few hours.

Thanks again for posting this issue mate, gave me the nudge I needed to get this done. Happy coding!

**Comment by PierBover** [comment]
Thanks for the quick fix!
