### ISSUE TITLE
Await blocks sometimes highlight brackets

### ISSUE THREAD

**Issue by ccampbell** [corneliusio/svelte-sublime#5]
Easiest to see with this screenshot:

![image](https://user-images.githubusercontent.com/259316/66719038-b3557b80-edb8-11e9-8065-491997e630a6.png)

See the opening backet of `{:then` and `{:catch` and `{/await` is highlighted. This does not seem to be the case with if/else statements.

**Comment by corneliusio** [comment]
Will start taking a look into this! Again, I apologize for not ever getting to this before now, ha.

**Comment by corneliusio** [comment]
I have not been able to replicate this issue. If you're still interested in working out a solution you can send over some more details such as build of Sublime text you're using, your current color scheme theme, and a full code example that the issue occurs in. Otherwise I will close this out if I don't hear back.

You could also try uninstalling and reinstalling the package to see if that works out any issues.
